version: '3.3'
services:
  plainsync:
    image: local/plainsync
    build: .
    container_name: plainsync-server
    ports:
      - '9999:9999'
    volumes:
      - ./data:/plainsync/data
      - /etc/localtime:/etc/localtime:ro
